function opts = solver_options(cfg)
%TARIFFWAR.SOLVER.SOLVER_OPTIONS  Build fsolve options from config.
%
%   opts = tariffwar.solver.solver_options(cfg)
%
%   Uses optimoptions (not legacy optimset) to properly set the algorithm.

    opts = optimoptions('fsolve', ...
        'Display',              cfg.solver.Display, ...
        'MaxFunctionEvaluations', cfg.solver.MaxFunEvals, ...
        'MaxIterations',        cfg.solver.MaxIter, ...
        'FunctionTolerance',    cfg.solver.TolFun, ...
        'StepTolerance',        cfg.solver.TolX, ...
        'Algorithm',            cfg.solver.algorithm);
end
