function raw = insample_itpd()
%TARIFFWAR.ELASTICITY.SOURCES.INSAMPLE_ITPD  In-sample CP2014 elasticities for ITPD.
%
%   raw = tariffwar.elasticity.sources.insample_itpd()
%
%   Returns 16x1 epsilon vector at WIOD-16 classification, estimated using
%   the Caliendo & Parro (2014) trilateral gravity methodology applied
%   directly to pooled ITPD trade flows and Teti tariffs (2000-2019).
%
%   Native ITPD sectors (153 goods + 1 services) are aggregated to the
%   16 broad WIOD groups (sum trade flows, average tariffs) before
%   estimation.
%
%   Classification: wiod_16 (maps to other datasets via concordance chain)
%
%   See also: tariffwar.elasticity.estimate_cp2014, tariffwar.elasticity.registry

    % WIOD-16: 15 goods + 1 services
    % Estimated from pooled ITPD 2000-2019, aggregated to WIOD-16
    % FE specification: OLS with country FE, HC1 robust SE, no constant
    raw.epsilon = [ ...
         5.5110;  ... % 1  Agriculture, forestry, fishing (pooled 1+2)
         5.5110;  ... % 2  Mining and quarrying (pooled 1+2)
         1.5484;  ... % 3  Food products, beverages, tobacco
         5.1442;  ... % 4  Textiles, wearing apparel, leather
         5.0685;  ... % 5  Wood, paper, printing
         0.2174;  ... % 6  Coke and refined petroleum
         6.1666;  ... % 7  Chemicals and pharmaceuticals
         3.6567;  ... % 8  Rubber, plastics, non-metallic minerals
         3.7311;  ... % 9  Basic metals
         5.6125;  ... % 10 Fabricated metals
         5.6163;  ... % 11 Computer, electronic, optical
         4.0257;  ... % 12 Electrical equipment
         2.4432;  ... % 13 Machinery and equipment
         6.7538;  ... % 14 Transport equipment
         3.6975;  ... % 15 Other manufacturing; repair
         4.0000]; ... % 16 Services (aggregate, fallback)

    raw.sectors = { ...
        'Agriculture, forestry, fishing'; ...
        'Mining and quarrying'; ...
        'Food products, beverages, tobacco'; ...
        'Textiles, wearing apparel, leather'; ...
        'Wood, paper, printing'; ...
        'Coke and refined petroleum'; ...
        'Chemicals and pharmaceuticals'; ...
        'Rubber, plastics, non-metallic minerals'; ...
        'Basic metals'; ...
        'Fabricated metals'; ...
        'Computer, electronic, optical'; ...
        'Electrical equipment'; ...
        'Machinery and equipment n.e.c.'; ...
        'Transport equipment'; ...
        'Other manufacturing; repair'; ...
        'Services (aggregate)'};
end
