function raw = insample_icio()
%TARIFFWAR.ELASTICITY.SOURCES.INSAMPLE_ICIO  In-sample CP2014 elasticities for ICIO.
%
%   raw = tariffwar.elasticity.sources.insample_icio()
%
%   Returns 16x1 epsilon vector at WIOD-16 classification, estimated using
%   the Caliendo & Parro (2014) trilateral gravity methodology applied
%   directly to pooled ICIO trade flows and Teti tariffs.
%
%   Native ICIO sectors are aggregated to the 16 broad WIOD groups
%   (sum trade flows, average tariffs) before estimation.
%
%   Classification: wiod_16 (maps to other datasets via concordance chain)
%
%   See also: tariffwar.elasticity.estimate_cp2014, tariffwar.elasticity.registry

    % WIOD-16: 15 goods + 1 services
    % Estimated from pooled ICIO 2011-2022, aggregated to WIOD-16
    % FE specification: OLS with country FE, HC1 robust SE, no constant
    raw.epsilon = [ ...
         7.6215;  ... % 1  Agriculture, forestry, fishing (pooled 1+2)
         7.6215;  ... % 2  Mining and quarrying (pooled 1+2)
         1.2925;  ... % 3  Food products, beverages, tobacco
         3.2191;  ... % 4  Textiles, wearing apparel, leather
         5.8568;  ... % 5  Wood, paper, printing
         6.3971;  ... % 6  Coke and refined petroleum
         7.7621;  ... % 7  Chemicals and pharmaceuticals
         3.0765;  ... % 8  Rubber, plastics, non-metallic minerals
         1.6119;  ... % 9  Basic metals (pooled 9+10)
         1.6119;  ... % 10 Fabricated metals (pooled 9+10)
         4.0000;  ... % 11 Computer, electronic, optical (pooled 11-15, fallback)
         4.0000;  ... % 12 Electrical equipment (pooled 11-15, fallback)
         4.0000;  ... % 13 Machinery and equipment (pooled 11-15, fallback)
         4.0000;  ... % 14 Transport equipment (pooled 11-15, fallback)
         4.0000;  ... % 15 Other manufacturing; repair (pooled 11-15, fallback)
         4.0000]; ... % 16 Services (aggregate, fallback)

    raw.sectors = { ...
        'Agriculture, forestry, fishing'; ...
        'Mining and quarrying'; ...
        'Food products, beverages, tobacco'; ...
        'Textiles, wearing apparel, leather'; ...
        'Wood, paper, printing'; ...
        'Coke and refined petroleum'; ...
        'Chemicals and pharmaceuticals'; ...
        'Rubber, plastics, non-metallic minerals'; ...
        'Basic metals'; ...
        'Fabricated metals'; ...
        'Computer, electronic, optical'; ...
        'Electrical equipment'; ...
        'Machinery and equipment n.e.c.'; ...
        'Transport equipment'; ...
        'Other manufacturing; repair'; ...
        'Services (aggregate)'};
end
